### ISSUE TITLE
Github Action document update

### ISSUE THREAD

**Issue by utamori** [pnpm/pnpm.github.io#154]
The setup-node action seems to support pnpm caching

https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

```yml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# NOTE: pnpm caching support requires pnpm version >= 6.10.0

steps:
- uses: actions/checkout@v2
- uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
  with:
    version: 6.10.0
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    cache: 'pnpm'
- run: pnpm install
- run: pnpm test

```
