### ISSUE TITLE
Example CI config for AWS CodeBuild 

### ISSUE THREAD

**Issue by dwiyatci** [pnpm/pnpm.github.io#296]
Hi, since there is no example config for integrating `pnpm` with CodeBuild listed yet in https://pnpm.io/continuous-integration, I wonder if anybody's ever done it before (and probably could suggest an "ideal" config for it). So far I've come up with the following config (simplified) but just not 100% sure if setting the pnpm's home/store somewhere in the current workdir is a good idea or not:
```yaml
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      - pnpm config set store-dir pnpm/store
  pre_build:
    on-failure: ABORT
    commands:
      - WORKDIR=$(pwd)
      - PNPM_HOME="${WORKDIR}/pnpm"
  build:
    commands:
      - pnpm install

```

Thank you!! 🙇🏻‍♂️
